[package]
name = "sha2-chain-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []
field-inline = ["jolt/field-inline"]

[dependencies]
jolt = { package = "jolt-sdk", git = "https://github.com/a16z/jolt", rev = "70a294ad58629af59ab89f646d6d0079b57174cb" }
jolt-inlines-sha2 = { git = "https://github.com/a16z/jolt", rev = "70a294ad58629af59ab89f646d6d0079b57174cb" }
